"""refacto_datalake_minio_et_metriques_temporelles

Revision ID: 44706f5edf55
Revises: 95b6f436028c
Create Date: 2026-07-05 18:04:23.790955

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '44706f5edf55'
down_revision: Union[str, Sequence[str], None] = '95b6f436028c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('crawler_state', sa.Column('crawler_mode', sa.String(), server_default='DISCOVERY_AND_DETAILS', nullable=False))
    op.drop_column('crawler_state', 'extraction_only')
    op.add_column('match_participants', sa.Column('gold_diff_15m', sa.Integer(), nullable=True))
    op.add_column('match_participants', sa.Column('xp_diff_15m', sa.Integer(), nullable=True))
    op.add_column('match_participants', sa.Column('is_snowballing', sa.Boolean(), nullable=True))
    op.add_column('matches', sa.Column('timeline_status', sa.String(), server_default='PENDING', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('matches', 'timeline_status')
    op.drop_column('match_participants', 'is_snowballing')
    op.drop_column('match_participants', 'xp_diff_15m')
    op.drop_column('match_participants', 'gold_diff_15m')
    op.add_column('crawler_state', sa.Column('extraction_only', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=False))
    op.drop_column('crawler_state', 'crawler_mode')
    # ### end Alembic commands ###
