"""ajout_table_aggregation_global_champion_time_stats

Revision ID: 6aef2b807f38
Revises: 44706f5edf55
Create Date: 2026-07-06 02:28:36.930162

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6aef2b807f38'
down_revision: Union[str, Sequence[str], None] = '44706f5edf55'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('global_champion_time_stats',
    sa.Column('champion_id', sa.Integer(), nullable=False),
    sa.Column('lane', sa.String(), nullable=False),
    sa.Column('duration_bucket', sa.Integer(), nullable=False),
    sa.Column('matches_count', sa.Integer(), nullable=False),
    sa.Column('wins_count', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('champion_id', 'lane', 'duration_bucket')
    )
    op.create_index(op.f('ix_global_champion_time_stats_champion_id'), 'global_champion_time_stats', ['champion_id'], unique=False)
    op.create_index(op.f('ix_global_champion_time_stats_lane'), 'global_champion_time_stats', ['lane'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_global_champion_time_stats_lane'), table_name='global_champion_time_stats')
    op.drop_index(op.f('ix_global_champion_time_stats_champion_id'), table_name='global_champion_time_stats')
    op.drop_table('global_champion_time_stats')
    # ### end Alembic commands ###
