"""ajout_coordonnees_jungle_pathing

Revision ID: 87239a156b6a
Revises: 275dc9d72a7f
Create Date: 2026-07-08 00:45:22.991100

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '87239a156b6a'
down_revision: Union[str, Sequence[str], None] = '275dc9d72a7f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('match_participants', sa.Column('pos_f1_x', sa.Integer(), nullable=True))
    op.add_column('match_participants', sa.Column('pos_f1_y', sa.Integer(), nullable=True))
    op.add_column('match_participants', sa.Column('pos_f2_x', sa.Integer(), nullable=True))
    op.add_column('match_participants', sa.Column('pos_f2_y', sa.Integer(), nullable=True))
    op.add_column('match_participants', sa.Column('pos_f3_x', sa.Integer(), nullable=True))
    op.add_column('match_participants', sa.Column('pos_f3_y', sa.Integer(), nullable=True))
    
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    
    op.drop_column('match_participants', 'pos_f3_y')
    op.drop_column('match_participants', 'pos_f3_x')
    op.drop_column('match_participants', 'pos_f2_y')
    op.drop_column('match_participants', 'pos_f2_x')
    op.drop_column('match_participants', 'pos_f1_y')
    op.drop_column('match_participants', 'pos_f1_x')
    
    # ### end Alembic commands ###
