"""ajout_extraction_only_crawler

Revision ID: 95b6f436028c
Revises: 9b88e5db0c28
Create Date: 2026-07-03 22:24:29.857131

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '95b6f436028c'
down_revision: Union[str, Sequence[str], None] = '9b88e5db0c28'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('crawler_state', sa.Column('extraction_only', sa.Boolean(), server_default='false', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('crawler_state', 'extraction_only')
    # ### end Alembic commands ###
