"""ajout_architecture_crawler

Revision ID: 9b88e5db0c28
Revises: c97af5736d12
Create Date: 2026-07-03 19:03:29.408840

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9b88e5db0c28'
down_revision: Union[str, Sequence[str], None] = 'c97af5736d12'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('crawler_match_queue',
    sa.Column('match_id', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('discovered_at', sa.BigInteger(), nullable=False),
    sa.PrimaryKeyConstraint('match_id')
    )
    op.create_index(op.f('ix_crawler_match_queue_match_id'), 'crawler_match_queue', ['match_id'], unique=False)
    op.create_index(op.f('ix_crawler_match_queue_status'), 'crawler_match_queue', ['status'], unique=False)
    op.create_table('crawler_queue',
    sa.Column('puuid', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('discovery_depth', sa.Integer(), nullable=False),
    sa.Column('discovered_at', sa.BigInteger(), nullable=False),
    sa.PrimaryKeyConstraint('puuid')
    )
    op.create_index(op.f('ix_crawler_queue_puuid'), 'crawler_queue', ['puuid'], unique=False)
    op.create_index(op.f('ix_crawler_queue_status'), 'crawler_queue', ['status'], unique=False)
    op.create_table('crawler_state',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('total_requests_made', sa.Integer(), nullable=False),
    sa.Column('current_rate_limit_sleep', sa.Integer(), nullable=False),
    sa.Column('started_at', sa.BigInteger(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('matches', sa.Column('is_crawled', sa.Boolean(), server_default='false', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('matches', 'is_crawled')
    op.drop_table('crawler_state')
    op.drop_index(op.f('ix_crawler_queue_status'), table_name='crawler_queue')
    op.drop_index(op.f('ix_crawler_queue_puuid'), table_name='crawler_queue')
    op.drop_table('crawler_queue')
    op.drop_index(op.f('ix_crawler_match_queue_status'), table_name='crawler_match_queue')
    op.drop_index(op.f('ix_crawler_match_queue_match_id'), table_name='crawler_match_queue')
    op.drop_table('crawler_match_queue')
    # ### end Alembic commands ###
