"""Init schema avec profil joueur

Revision ID: c97af5736d12
Revises: 
Create Date: 2026-06-23 17:07:40.663657

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'c97af5736d12'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('matches',
    sa.Column('match_id', sa.String(), nullable=False),
    sa.Column('game_version', sa.String(), nullable=False),
    sa.Column('game_duration', sa.Integer(), nullable=False),
    sa.Column('creation_timestamp', sa.BigInteger(), nullable=False),
    sa.Column('raw_match_data', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.PrimaryKeyConstraint('match_id')
    )
    op.create_index(op.f('ix_matches_game_version'), 'matches', ['game_version'], unique=False)
    op.create_index(op.f('ix_matches_match_id'), 'matches', ['match_id'], unique=False)
    op.create_table('players',
    sa.Column('puuid', sa.String(), nullable=False),
    sa.Column('summoner_id', sa.String(), nullable=True),
    sa.Column('riot_id_name', sa.String(), nullable=False),
    sa.Column('riot_id_tagline', sa.String(), nullable=False),
    sa.Column('profile_icon_id', sa.Integer(), nullable=True),
    sa.Column('summoner_level', sa.Integer(), nullable=True),
    sa.Column('tier', sa.String(), nullable=True),
    sa.Column('rank', sa.String(), nullable=True),
    sa.Column('league_points', sa.Integer(), nullable=True),
    sa.Column('last_update_timestamp', sa.BigInteger(), nullable=True),
    sa.PrimaryKeyConstraint('puuid')
    )
    op.create_index(op.f('ix_players_puuid'), 'players', ['puuid'], unique=False)
    op.create_index(op.f('ix_players_summoner_id'), 'players', ['summoner_id'], unique=False)
    op.create_table('match_participants',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('match_id', sa.String(), nullable=False),
    sa.Column('puuid', sa.String(), nullable=False),
    sa.Column('team_id', sa.Integer(), nullable=False),
    sa.Column('champion_id', sa.Integer(), nullable=False),
    sa.Column('lane', sa.String(), nullable=False),
    sa.Column('position', sa.String(), nullable=False),
    sa.Column('win', sa.Boolean(), nullable=False),
    sa.Column('kills', sa.Integer(), nullable=False),
    sa.Column('deaths', sa.Integer(), nullable=False),
    sa.Column('assists', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['match_id'], ['matches.match_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['puuid'], ['players.puuid'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('match_id', 'puuid', name='uix_match_puuid')
    )
    op.create_index('ix_participant_filter', 'match_participants', ['puuid', 'position', 'champion_id'], unique=False)
    op.create_table('match_timelines',
    sa.Column('match_id', sa.String(), nullable=False),
    sa.Column('raw_timeline_data', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.ForeignKeyConstraint(['match_id'], ['matches.match_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('match_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('match_timelines')
    op.drop_index('ix_participant_filter', table_name='match_participants')
    op.drop_table('match_participants')
    op.drop_index(op.f('ix_players_summoner_id'), table_name='players')
    op.drop_index(op.f('ix_players_puuid'), table_name='players')
    op.drop_table('players')
    op.drop_index(op.f('ix_matches_match_id'), table_name='matches')
    op.drop_index(op.f('ix_matches_game_version'), table_name='matches')
    op.drop_table('matches')
    # ### end Alembic commands ###
